[build]
  # Directory to deploy (where your HTML files are)
  publish = "public/"
  
  # No build command needed for static files
  command = "echo 'No build required'"

[functions]
  # Directory containing serverless functions
  directory = "netlify/functions"

[dev]
  # Local development settings
  publish = "public/"
  port = 8888
  
# Headers for security (optional but recommended)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
